services:
  node:
    build:
      context: ..
      dockerfile: docker/node/Dockerfile

    volumes:
      - ..:/usr/src/app
      - node_modules:/usr/src/app/node_modules

    extra_hosts:
      - 'host.docker.internal:host-gateway'

    ports:
      - '51204:51204'
      - '5173:5173'

    env_file:
      - node/envVars.public

    stdin_open: true
    tty: true

volumes:
  node_modules:
